### PR TITLE
api plugin config change

### PR DESCRIPTION
**Pull request by sgarlick987**
Hi, I had been seeing an issue with api plugin configs where they would randomly be updated/missing due to map ordering and how terraform does the comparisons (as far as I could tell that is). This mainly changes the config format in the kong_api_plugin resource to

```
    config {
        name = "minute"
        value = "100"
    }
    config {
        name = "policy"
        value = "cluster"
    }
```
I also had vendored the latest dependencies and cleaned up some small warnings. I can take those out if you don't want that as well.

Thanks.

### CODE REVIEW

**Comment by martinivanov** [comment]
@sgarlick987, thank you for the contribution! Regarding the dependencies, is it common to include them to the project in this way?

**Comment by sgarlick987** [comment]
Seems like terraform itself does https://github.com/hashicorp/terraform/blob/master/vendor/vendor.json . Most other golang projects I've seen on github do too. As far as I understand the idea is that go uses the /vendor folder for looking up our dependencies so we can have repeatable builds and control dependency versions via a too (I've been using govendor for managing this here).

**Comment by martinivanov** [comment]
I see, it makes sense. 

Regarding the issue with the differences in the plugin configs - I debugged it and it seems it's not the order, but the fact, that kong adds default values to some configurations. For example, if we only add the _minute_ config to the rate limiting plugin, kong will add the _limit_by_ config with a default value of "consumer". When terraform diffs the resource during plan or apply, it will read the config and note the difference. I've made a fix [here](https://github.com/WeKnowSports/terraform-provider-kong/commit/0d619afaac81a2468e32760b4ac89bf8b4bf1eef#diff-d117776972e42e44f522606c0073503a). It doesn't change the interface and seems to fix the problem.

**Comment by sgarlick987** [comment]
Ok cool, this my first time modifying terraform plugins so wasn't too sure how to debug. I'll test out your change and nuke this PR. The only thing that slightly confuses me is that when I would rerun the plan I would get completely different changes each time (sometimes would show seconds "" -> "number" and sometimes would not show that at all and other times a different config field). I'll test that out now to verify too.

**Comment by sgarlick987** [comment]
That does seem to take care of it. Closing this PR. Thanks again.

**Pull request closed without merging**
